# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e85747e726a5dec8ad3d9280cfa323df65516869e6f49a631a7fa3e29113610ca8984712b2c87c4539b9e930535676d24ce2e11afcc359ab10d21dd2702cc0a

test:
  secret_key_base: 91eff4887bdeff937e866df53a1e50166e01aa304ae77d9e57ca5ce498e3d7c8e0b1e5bd67f6d4c1bef0c2503c4fabfe373f0bb3506706f7d08d812f7578ebf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
